added cart page
KanekarSnehal/magnet-store-ecom pull request #7
Opened 2022-03-25 10:24 UTC by KanekarSnehal

Added cart page with following functionality
- user can add product to cart from product-listing page and also wishlist page
- once product is added to cart from product-listing page the button will change to go to cart which will redirect the user to cart.
- if the product is added to cart from wishlist once then further the quantity of that product will be increased.
- On the cart page the quantity of product can be incremented/decremented and also product can be moved to wishlist if it does not exist in wishlist else user will get the option of remove from wishlist.
- User can also directly remove the product from the cart.
- The Cart Billboard shows the Total MRP, Total discount on MRP and the Total Amount to be paid.

2022-03-25 10:51 UTC, Isha2806 approved these changes
Snehal I must say, a splendid App is in progress!  
I like how descriptive the Pr is. For UI, the color looks good to my eyes. 
you can improve more on styling later when all the functionalities are done.

2022-03-25 10:51 UTC, Isha2806 commented on src/api-calls/addToCart.js
> +
I am sure you will remove these extra spaces where its not  necessary later while refactoring your code.

2022-03-25 12:37 UTC, prathmeshjagtap requested changes
Everything seems to work fine, I liked how you have made small functions for each  task, such as increment  decrement items, also you have maintained constants separately

2022-03-25 22:06 UTC, Mohitkumar33 approved these changes
Nice and clean code with nice variable naming

2022-03-26 05:25 UTC, KanekarSnehal commented
> Snehal I must say, a splendid App is in progress! I like how descriptive the Pr is. For UI, the color looks good to my eyes. you can improve more on styling later when all the functionalities are done.

Thank you Isha for your feedback, I will work on styling later on.

2022-03-26 05:26 UTC, KanekarSnehal commented
> Everything seems to work fine, I liked how you have made small functions for each task, such as increment decrement items, also you have maintained constants separately

Thank you for your feedback.

2022-03-26 05:26 UTC, KanekarSnehal commented
> Nice and clean code with nice variable naming

Thank you Mohit

2022-03-26 05:26 UTC, merged